### ISSUE TITLE
Blurry image

### ISSUE THREAD

**Issue by bakory91** [hacksider/Deep-Live-Cam#1229]
i got blur face when i run the model
[

![Image](https://github.com/user-attachments/assets/ec8a064e-2a83-4c32-bb5e-b1fc4dfdcd82)

](url)

**Comment by prologlover** [comment]
> the face enhancer activated? If not

same problem

**Comment by prologlover** [comment]
The problem solved by downloading another version of (inswapper_128_fp16)

**Comment by ifinduway** [comment]
I have the same problem
models: GFPGANv1.4 / inswapper_128_fp16

![Image](https://github.com/user-attachments/assets/7d4cc1b0-9097-40e1-aff7-631394659370)

**Comment by cann4a** [comment]
> I have the same problem models: GFPGANv1.4 / inswapper_128_fp16
> 
> ![Image](https://github.com/user-attachments/assets/7d4cc1b0-9097-40e1-aff7-631394659370)

Try to download the inswapèper_128_fp16 model again from https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/inswapper_128_fp16.onnx and substitute it with the current one

**Comment by CubM** [comment]
I fixed the same issue by downloading the 32 model and renaming it to fp16

**Comment by Jandown** [comment]
> > I have the same problem models: GFPGANv1.4 / inswapper_128_fp16
> > ![Image](https://github.com/user-attachments/assets/7d4cc1b0-9097-40e1-aff7-631394659370)
> 
> Try to download the inswapèper_128_fp16 model again from https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/inswapper_128_fp16.onnx and substitute it with the current one

Problem solved, thank you very much.

**Comment by Jefsky** [comment]
> > 我有相同的问题模型：GFPGANv1.4 / inswapper_128_fp16
> > ![Image](https://github.com/user-attachments/assets/7d4cc1b0-9097-40e1-aff7-631394659370)
> 
> [](https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/inswapper_128_fp16.onnx)尝试从 https://github.com/facefusion/facefusion-assets/releases/download/models-3.0.0/inswapper_128_fp16.onnx 再次下载 inswapèper_128_fp16 模型并将其替换为当前模型

确实可以！非常感谢~

**Comment by suuuperfrankie** [comment]
Testing comment fetch

**Comment by obsidianocean** [comment]
to whoever still have this problem, don't have the deep-live-cam folder save at any system folder that may require admin permission such as SYSTEM32, USER/DOCUMENTS, etc. Move you repo to anywhere even your desktop works
